### ISSUE TITLE
Matrix matching of layouts

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#102]
The layouts should be stored in db based on a key, not based on the exact URL. The order of applications should not matter. 

**Matching of layouts**
When there is layout saved for 3 out of 4 apps on the screen, the already made layout for the 3 apps should be used while the layout for the 4th app should be generated on-the-fly. 

**Merging layout definitions from suites**
Suites will come as sets of app dependencies with proposed layout. When we have 2 suites that use 4 apps on the same screen, the generated layout should be derived from layout defined in the suites.

Discussed with @Starcounter-Jack and @tomalec on Monday

**Comment by miyconst** [comment]
@warpech this is already fixed, correct?

**Comment by warpech** [comment]
Not really. This issue what about composing a merged layout of of saved partial layouts. Let's close this because there are no action points.
