### ISSUE TITLE
Allow editing of merged template HTML

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#103]
As discussed today with @Starcounter-Jack 

It would be nice if the HTML resulting from `/polyjuice-merger` would be hackable so that I can edit it and provide my own version of it (so that I can add my own stuff to the templates on the fly, or test new concepts without touching the file system).

Whether it should be stored on server is a different thing. LocalStorage may be fine for the beginning. Maybe this should be done as part of the `<starcounter-debug-aid>`?

**Comment by warpech** [comment]
@tomalec seems that our recent idea is not that new :)

**Comment by tomalec** [comment]
Yep :) I try to keep my ideas an proposition consistent with all vital constraints we provided so far.

**Comment by warpech** [comment]
Closing as this is currently possible with the simple layout editor
