### ISSUE TITLE
Add end-to-end test with Selenium

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#106]
We discussed end-to-end test with @parherman and the idea for simple end to end test is:

1. In each application repo (Launcher for beginning), create a `test` subdirectory.
2. Inside, create a Node script that tests with Selenium, whether:
  - root `text/html` request results in expected response
  - root `application/json` request results in expected response
  - /_db/<SessionID> `application/json-patch+json` request results in expected response (Marcin to provide example)
3. Before pushing code, developer should verify if the test passes
4. As part of the nightly build, the build server will verify if the test passes

In future, we might have multiple test suites in the `test` directory, such as:
- `test/selenium` for end-to-end tests
- `test/NUnit` for unit tests in C# apps
- `test/mocha` for unit tests in JS apps

**Comment by parherman** [comment]
I have added initial tests for Launcher in commit 0e691789e2845fe19e11004e0e18d0c6ca21a9dc

**Comment by warpech** [comment]
We should only do Selenium test at this moment in Launcher, because other tests are covered by platform tests. Launcher is strictly UI based.

**Comment by warpech** [comment]
Selenium tests are being added to KitchenSink first: https://github.com/StarcounterSamples/KitchenSink/issues/18

**Comment by warpech** [comment]
I have written an article about using Selenium: http://starcounter.io/guides/web/acceptance-testing-with-selenium/

**Comment by dan31** [comment]
Awesome work @warpech!

**Comment by warpech** [comment]
Closing, as there are Selenium tests now in Launcher: https://github.com/StarcounterPrefabs/Launcher/tree/master/test/Launcher_AcceptanceTest
