### ISSUE TITLE
Define desired behavior for layouts and layouts manager

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Launcher#137]
As mentioned in https://github.com/Juicy/juicy-tile-grid/issues/8#issuecomment-112030320
We need more precisely stated expectations, and test cases,for what we really want to achieve with layouts in various scenarios, mixing:
- use of different units, and fixed/flexible dimensions for individual elements,
- behavior when new apps are started,
- when app get's stopped, and their elements were part of already custom defined layout,
  - should gap grow relatively to nesting level, or to the size of a window as well,
- etc.

pictures, and/or HTML examples are more than needed

**Comment by warpech** [comment]
Closing, because it is related to the old layout editor which was phased out.
