### ISSUE TITLE
Consider making bin-packing applicable only if explicitly asked

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Launcher#138]
(as mentioned in https://github.com/Juicy/juicy-tile-grid/issues/8#issuecomment-112030320)

If we speak on layout, we usually mean eye candy layout prepared for given set of elements by aesthetically inclined professional, and we speak in position, dimensions, relation to other elements.
We rarely think of linear (`priority`) order, and effective use of space.

So, as gap-less layout definitely may be useful for default, or initial layout, we may make it more on-demand.
For example, when there is no custom grid layout, and user clicks "arrange tiles automatically" button.

**Comment by warpech** [comment]
Closing, because it is related to the old layout editor which was phased out.
