### ISSUE TITLE
Remove the padding/Margin in the "workspace"?

### ISSUE THREAD

**Issue by andwah** [StarcounterPrefabs/Launcher#139]
How do i remove that "gap"

![image](https://cloud.githubusercontent.com/assets/2656996/8160715/25364e58-1372-11e5-9371-7418c4f2bb83.png)

**Comment by miyconst** [comment]
@andwah I tried to run AppStoreClient locally, but was not able to build the app:
```
'Starcounter.Node' does not contain a definition for 'LocalhostSystemPortNode'	E:\GitHub\AppStoreClient\src\AppStoreClient\ViewModels\ListAppStoreAppsPage.json.cs	Line:11	Column:38
```

Could you please make sure that everything is commited, and if yes then what could cause this error?

**Comment by andwah** [comment]
At the moment the AppStoreClient working code is in the "newadmin" branch. https://github.com/Polyjuice/AppStoreClient/tree/newadmin

the "newadmin" branch will soon be the "master" branch

**Comment by andwah** [comment]
btw. i think this "gap" is in the launcher and not defined in the app itself.

**Comment by miyconst** [comment]
Yes, this gap is defined in launcher styles: https://github.com/Polyjuice/Launcher/blob/master/src/Launcher/wwwroot/Launcher/css/style.css#L20

I can remove it, if you need. For me AppStore looks better with the gap.

**Comment by warpech** [comment]
This gap is configurable in Launcher's CSS right now. It will be
configurable in Launcher's layout editor one day. It does not come from the
app.

--
Marcin Warpechowski
+48 603 607 801

**Comment by miyconst** [comment]
The new editor highlights the editable area. Should no longer be an issue.

**Comment by warpech** [comment]
I agree. Closing
