### ISSUE TITLE
Noise app should be able to respond to any request

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Launcher#14]
It seems wildcards in URL Handler behaves incorrectly in case of `{?}/{?}` or `{?}` if selected part may contain `/`

Check [NoiseApp](https://github.com/Polyjuice/Launcher/tree/NoiseApp) branch

**Comment by miyconst** [comment]
@tomalec is this issue still up to date?

**Comment by warpech** [comment]
Noise app was archived and is not available anymore. This issue is outdated and the problem is already tracked in https://github.com/Starcounter/Starcounter/issues/1568. Besides, it should be solvable with middleware filters.
