### ISSUE TITLE
Sometimes launchpad is not rendered

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#150]
See the screenshot:

<img width="1552" alt="screenshot 2015-08-18 15 57 39" src="https://cloud.githubusercontent.com/assets/566463/9345028/fa4f7d22-45c1-11e5-8823-7ffc21dc3020.png">

This is related to the Polymer errors highlighted in yellow.

**Comment by miyconst** [comment]
@warpech have you met this bug recently?

**Comment by warpech** [comment]
Not exactly the same one. Closing
