### ISSUE TITLE
Bootstrap connection fails with 400, if server-side was restarted, and browse still has the cookie

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Launcher#153]
We should renew session more gracefully.
Steps to reproduce:
1. goto /launcher
2. restart Launcher app
3. refresh the page

**Comment by tomalec** [comment]
@warpech, @alemoi WDYT?

Someone have to invalidate/renew/clear the cookie.

Browser cannot do so, until it asks server. So either server may do so, or client after asking server, but this requires another ping-pong request.

**Comment by alemoi** [comment]
Maybe if session info is wrong the request should be treated as without session?

**Comment by warpech** [comment]
Since 2015 we have new caching rules (https://github.com/Starcounter/Starcounter/issues/3427).

Since today there is no Location cookie (https://github.com/Starcounter/Starcounter/issues/3798).

Closing as fixed with other fixes.
