### ISSUE TITLE
Use CSS Grid Layout shim

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#159]
Currently Launcher (actually juicy-tile-grid) only works in Chrome/Opera, which support CSS Grid Layout (but only with "Enable experimental web platform features" enabled).

Investigate using a CSS Grid Layout shim so that Launcher becomes usable in FF & Edge.

**Comment by tomalec** [comment]
I have added issue on juicy repo https://github.com/Juicy/juicy-tile-grid/issues/29
With full list of CSS Grid & Shadow DOM support.

CSS Grid works fine in IE, but there are other issues that might be tracked under https://github.com/StarcounterSamples/Launcher/issues/175

**Comment by miyconst** [comment]
@warpech can we close this issue as we use `juicy-tile-table`?

**Comment by warpech** [comment]
Yes, definitely
