### ISSUE TITLE
Decide what to do with filter

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#16]
Decide what to do with filter:

![image](https://cloud.githubusercontent.com/assets/2656996/2788569/657091cc-cb9d-11e3-8fff-57d2ef64865e.png)

 - if we keep it
   - style it (Anders)
   - make it functional (Marcin)
 - if we don’t keep it, remove it from the template (Anders)

**Comment by miyconst** [comment]
@warpech this is is outdated, right?

**Comment by warpech** [comment]
Yes, this is totally outdated. The filter in topic was never implemented and was removed from the UI more than a year ago.
