### ISSUE TITLE
Workspaces need to turn off AutoRefreshBoundProperties when in background

### ISSUE THREAD

**Issue by malx122** [StarcounterPrefabs/Launcher#160]
As the title. You can not have "cached" workspaces in background that auto refresh properties. That can get totally out of hands after a while and many apps.

**Comment by warpech** [comment]
The thing is that server has no knowledge about what workspaces are "in background". For the server, all of them are equal JSON subtrees.

@chrhol any options here? we could potentially use request filters to log what is the last accessed URL to know what is the current workspace.

**Comment by malx122** [comment]
Launcher or server should know... Someone divides the requests into workspaces and that someone knows which was the last requested.

**Comment by warpech** [comment]
Done in https://github.com/StarcounterPrefabs/Launcher/issues/215
