### ISSUE TITLE
Multiple workspaces per app.

### ISSUE THREAD

**Issue by malx122** [StarcounterPrefabs/Launcher#161]
Only one "cached" workspace per app is not enough. There must be some way to do this better then to just bind it against the appname...

**Comment by warpech** [comment]
Could you please explain the use case / desired UX?

**Comment by malx122** [comment]
Single app has two "main" pages that you normally go back and forth between!
You don't want a full reload everytime. (But you want the one in background not to auto update before it is brought in front again to refer to my other issue)

**Comment by warpech** [comment]
This can be achieved by keeping these two views as separate branches in the master view-model of your app.

For example:

```
{
  Html: "",
  ListView: {},
  IsListViewFocused: false,
  DetailView: {},
  IsDetailViewFocused: true
}
```

**Comment by warpech** [comment]
Closing as answered. @malx122 please reopen if you disagree.
