### ISSUE TITLE
Selected app in menu

### ISSUE THREAD

**Issue by mattiasmak** [StarcounterPrefabs/Launcher#174]
In the launcher menu it would be great and logical to indicate currently active app. I see no obvious way now without a big mess. 

I guess the problem is the current approach with htmlmerger. This makes is difficult the do this rather simple thing without a javascript hack.

**Comment by warpech** [comment]
There is a duplicate of this issue that has slightly more info: https://github.com/StarcounterPrefabs/Launcher/issues/244

Closing this to avoid duplication.
