### ISSUE TITLE
Duplicated juicy-redirect?

### ISSUE THREAD

**Issue by andwah** [StarcounterPrefabs/Launcher#179]
Should juicy-redirect be included in the launcher and in starcounter clientfiles? at the moment this is the case.

**Comment by warpech** [comment]
Every app should include it's own dependencies, so yes.

**Comment by andwah** [comment]
how do i make sure that my app /sys/juicy-redirect  is loaded and not starcounter /sys/juicy-redirect 
they may have different versions?
I guess no apps should put stuff in /sys folder.

**Comment by tomalec** [comment]
>Every app should include it's own dependencies, so yes. There is no "the launcher", only "a launcher".

I would say, that is why no other app should rely on what in in Launcher, but I would say that apps (in this case Launcher) may rely on what is included in Starcounter.
So as Launcher does not include `fast-json-patch` it may import it relying on Starcounter's /sys

**Comment by andwah** [comment]
> Every app should include it's own dependencies, so yes. There is no "the launcher", only "a launcher".

So why does launcher inject stuff in \sys folder? If two apps will put a file in the \sys folder with the same file name but different content one file will override the other, then we will get different result depending on the order we start the apps i guess.

**Comment by tomalec** [comment]
>So why does launcher inject stuff in \sys folder?
1. To make conventional bower dependencies work. Usually HTML Imports loads dependencies from `../` which in this case points to `/sys`
2. Sometimes (`<launcher-include>`) we do so to overwrite in purpose existing content (`<starcounter-include>`

>then we will get different result depending on the order we start the apps i guess.

We still need to find good solution to avoid accidental collisions. :/

**Comment by jwillmer** [comment]
FYI: At the moment juicy-redirect is not included in the launcher sys files. Only setup as source in bower.

**Comment by miyconst** [comment]
@tomalec this is fixed, right?

**Comment by tomalec** [comment]
Yes. It is included in Starcounter's `/sys` https://github.com/Starcounter/Starcounter/tree/develop/src/BuildSystem/ClientFiles/StaticFiles/sys and in [Launcher's `bower.json`](https://github.com/StarcounterPrefabs/Launcher/blob/master/src/Launcher/bower.json) as it is required, but it is not attached to Launcher's sys,  as it is marked as ignored in [`.bowerrc`](https://github.com/StarcounterPrefabs/Launcher/blob/master/src/Launcher/.bowerrc), to avoid duplicates
