### ISSUE TITLE
Launcher is not a sample

### ISSUE THREAD

**Issue by Starcounter-Jack** [StarcounterPrefabs/Launcher#182]
The launcher appears to be a sample app whereas it is rather a prefab app. Consider changing organisation.

**Samples** sacrifice functionality and size/organisation to be small and simple. Their primary purpose is teaching. Samples might be used in production but not at the cost of being small and simple. Often they are used as a starting point.

**Prefabs** prioritise quality and are complete/functional even if it means more lines of code or increased complexity.  Prefabs are meant to be put to use in production as full members of the app composition.

**Comment by per-samuelsson** [comment]
Somewhat relate to #151 and https://github.com/Starcounter/CompanyTrack/issues/142.

**Comment by warpech** [comment]
...and https://github.com/Starcounter/CompanyTrack/issues/171

As agreed with @miyconst, I will create a new organisation StarcounterPrefabs and move there the prefabs from the list (Starcounter/CompanyTrack#142).

An alternative idea was to put prefabs to the Starcounter organisation, but this would mix the platform and the apps.

**Comment by warpech** [comment]
I copied the explanation of Samples vs Prefabs from the first post to GitBook.

**Comment by miyconst** [comment]
Launcher is now moved to StarcounterPrefabs. Closing this issue. @warpech open it, if you disagree.

**Comment by warpech** [comment]
:+1:
