### ISSUE TITLE
Graphics indicate that buttons are inactive although they are not

### ISSUE THREAD

**Issue by Starcounter-Jack** [StarcounterPrefabs/Launcher#184]
The style of the gray buttons indicate them being disabled rather than deselected. Better toggle button UX is needed.

<img width="220" alt="screenshot of google chrome 13-01-16 10-45-34" src="https://cloud.githubusercontent.com/assets/1219049/12290558/ccee30d6-b9e2-11e5-8bb0-af34f324b25e.png">

**Comment by warpech** [comment]
Closing, because it is related to the old layout editor which was phased out.
