### ISSUE TITLE
Resize with content does not do anything

### ISSUE THREAD

**Issue by Starcounter-Jack** [StarcounterPrefabs/Launcher#188]
Although i check this:

<img width="193" alt="screenshot of google chrome 13-01-16 11-16-45" src="https://cloud.githubusercontent.com/assets/1219049/12291379/2d2b0718-b9e7-11e5-8421-ee2e2f44551f.png">

The button remains 954 pixels.

<img width="389" alt="screenshot of google chrome 13-01-16 11-17-11" src="https://cloud.githubusercontent.com/assets/1219049/12291386/32bdea1a-b9e7-11e5-8533-3f9719b478b8.png">

**Comment by tomalec** [comment]
But how would you like it to resize?
It was packed to be 100% => occupy entire row
You also marked "resize-with content" which means that when your content will change, your tile wil streatch to make it fit.

Maybe you meant to (pre-) calculate?

**Comment by miyconst** [comment]
I think this issue should be closed as we designed new 3x3 control. https://github.com/Juicy/juicy-tile-editor/issues/121
