### ISSUE TITLE
Default layout for tiles

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Launcher#191]
As discussed today on a meeting by @Starcounter-Jack, @warpech, @miyconst, and @tomalec, we would remove `precalculate*` feature and phase from `juicy-tile-*`(, or at least `-table`, and `-grid`)

The main reason is to remove the FOUC, and improve performance and experience  on page load.

The constraints are: 
- we would like to serve something that makes sense even if no layout, metadata, hinds are provided,
- we would like it to play nice if some times gets meta-data, hints, and some don't,
- it should easy to modify with the editor.

The solution that we cam with is:
1. Pre-claculate phase will be removed =>
   - No FOUC, 
   - better performance, and
   - it would be easier to provide headless AI/robot-phase
2. `precalculate*` property will be disregarded,
3. We will provide a specific value for `height` (maybe `width` as well, for algorithmic symmetry), like `undefined`, or `null`, which would behave like any infinitesimal number greater than zero (ε). Thanks, to that bin-packing algorithm, would be able to pack it somewhere else than `0,0`.
   1. Bin-packing phase will treat it as ε or 1,
   2. Editor will search for all such values, and will calculate real numeric value, according to the current (rendered) layout context
4. Default tile setup would be:
   
   ``` js
   {
   width: "100%",
   height: null,// undefined/ε
   dynamicHeight: true // grow with content
   }
   ```
   
   Thanks, to that, by default bin-packing phase, would be forced to stack tiles, as each tile will occupy its own row, and will grow with content, they will get intrinsic height (as in natural DOM behavior, thanks, to CSS rules, not our magic, or re-invented wheel). Other tiles' setup will not affect this behavior, they would be selectable, and editable with editor, which would attach real value when needed/ asked.

**Comment by tomalec** [comment]
The doubts that came into my mind are:

1. Should we implement it also in `-grid`, or just leave it  until CSS Grid support comes? I think it's worth to keep it in `-list`, as with absolute positioned layout, we wold probably need to precalculate tile on resize to achieve "grow with content" behavior.
2. Should our magic value be:
 1. `undefined` gives the semantic meaning, but it would be hard to distinguish value set to `undefined` from not set, especially that Starcounter serializer have problems returning `undefined`s. But maybe we do not need to distinguish that, and simply apply this behavior if there is no `height` (`width` value)?
 2. `null` quite safe, but not so self-explanatory
 3. `ε` - math's beauty ;), quite self-explanatory (at least for math inclined folks), for micro optimization perspective, it's more expensive to compare strings, and it may be tricky as it's unicode character.
 4. `Number.EPSILON` - almost as beautiful as one above, but may have performance, comparison, and browser compatibility issues. However it could be used by bin-packing without any check, just as any other value, so the only check would be done by editor.
3. Should bin-packing, use `1` or `Number.EPSILON` as a size to render?


WDYT?

**Comment by miyconst** [comment]
1. I think we should not spend time on `juicy-tile-grid` for now, and should not remove these features from `juicy-tile-list`.
2. I like the `iii` and `iv` options with a little favour to `iii`.
3. Don't have enough input to have an opinion. `1px` is too small, what if we use `10px` instead?

**Comment by tomalec** [comment]
It's no longer an issue, as we use Full `DocumentFragment`s as layouts. See https://starcounter.io/layout-compositions-html-partials/
