### ISSUE TITLE
New UI for blending editor

### ISSUE THREAD

**Issue by Starcounter-Jack** [StarcounterPrefabs/Launcher#192]
Normally, users are expected to use the blending editor in the simplified mode. In this mode, the user chooses media range, the width of the widget and the relative order of the widget.

![blendingeditor](https://cloud.githubusercontent.com/assets/1219049/12537711/1bb779c0-c2c6-11e5-9618-403317301999.png)

**Comment by Starcounter-Jack** [comment]
The pixel size of the responsive media ranges changes according to the relative size of the partial. I.e. if the size of the partial is approximately 50% of the size of the browser, the pixel sizes are halved. 

![capture](https://cloud.githubusercontent.com/assets/1219049/12537622/8f1fb5d8-c2c3-11e5-8b4d-abbd162b757f.PNG)

![closeup2](https://cloud.githubusercontent.com/assets/1219049/12537623/90affa70-c2c3-11e5-9f0a-a3aac532d227.PNG)

**Comment by miyconst** [comment]
@Starcounter-Jack can you also make an image with opened "advanced" block?

Here http://juicy.github.io/juicy-tile-editor/simple.html you can see what is included under "More" and "Advanced" buttons.

**Comment by Starcounter-Jack** [comment]
Will do

**Comment by warpech** [comment]
@Starcounter-Jack nice! do you have an SVG or AI for that?

**Comment by tomalec** [comment]
Cool! :)
> if the size of the partial is approximately 50% of the size of the browser, the pixel sizes are halved. In this way, the responsive symbols will be operational also for nested partials

Theoretically partial size may also be highly flexible, but I think for basic view, providing defaults in such way should be really enough, as long, as:
>  In advanced mode, I suggest that the ranges could be specified manually.

The other question is that we would not be able to react on partial re-sizes within parent's range without element-queries, but we could react once parent is repacked due to it's media-query tick.

Maybe we could make something to emphasize the current value of a relative priority? As it is 0-1 number we could simply stroke some indicator (bullet/label/buttons) with color in opacity given by priority? For example button up will make it hotter/red, and button down cooler/blue/white

**Comment by Starcounter-Jack** [comment]
Adobe Illustrator file: 

https://www.dropbox.com/s/x9aixg36xqhpzkq/BlendingEditor.ai?dl=0

**Comment by warpech** [comment]
Thanks! For the AI! (@miyconst: @andwah should be able to convert it to other formats)

> Maybe we could make something to emphasize the current value of a relative priority? As it is 0-1 number we could simply stroke some indicator (bullet/label/buttons) with color in opacity given by priority? For example button up will make it hotter/red, and button down cooler/blue/white

Isn't it now obvious that the UP (▲) buttons moves elements closer to the top and DOWN (▼) closer to the bottom? For me that's more obvious than the hot/cold methaphor.

Please let's not discuss breakpoint architecture in this issue, because this will get really messy up here. @tomalec I propose that you write how you propose this to work in the GitBook. I will give you access to it.

**Comment by miyconst** [comment]
> ... For me that's more obvious than the hot/cold methaphor.

Agree. For me colors would be even more confusing.

>@miyconst: @andwah should be able to convert it to other formats

I can look for some online tools, but I don't have PS or AI.

@Starcounter-Jack how this image should zoom to 1920 px width screen? It looks huge when stretched to the entire width. Can you provide some dimensions?

**Comment by warpech** [comment]
@andwah has AI, so he's better than any online tool :)

**Comment by andwah** [comment]
@warpech where do you want me to put the converted file?

**Comment by miyconst** [comment]
@andwah could you please save each element as an png icon and put to dropbox?

**Comment by per-samuelsson** [comment]
> Isn't it now obvious that the UP (▲) buttons moves elements closer to the top and DOWN (▼) closer to the bottom? For me that's more obvious than the hot/cold methaphor.

Me too.

Nice flicks @Starcounter-Jack.

**Comment by miyconst** [comment]
Parent issue: https://github.com/Juicy/juicy-tile-editor/issues/98

**Comment by Starcounter-Jack** [comment]
![blendingeditor-simple](https://cloud.githubusercontent.com/assets/1219049/12580856/35bda7a4-c433-11e5-84b2-4456480ae6c8.png)
![blendingeditor-expert](https://cloud.githubusercontent.com/assets/1219049/12580857/35c17fd2-c433-11e5-97a9-0c49ca00f329.png)

**Comment by miyconst** [comment]
I like it! The only thing which confuses me is tab selection. Looks like "out of design".

@andwah could you please cut the icons off the AI file and save in png format?

**Comment by andwah** [comment]
@miyconst Sure,

**Comment by andwah** [comment]
@miyconst How do you want this part cut?

![image](https://cloud.githubusercontent.com/assets/2656996/12581879/b4704b50-c439-11e5-9fa9-c943bfc608f6.png)

**Comment by miyconst** [comment]
@andwah no, I don't need that. It could be done with css, even though I don't yet understand what it shows :)

**Comment by andwah** [comment]
@miyconst You can find the images in my dropbox/BlendingEditor folder 

![arrow down](https://cloud.githubusercontent.com/assets/2656996/12582226/16f9986a-c43c-11e5-96a3-b145a64cee24.png)
![arrow down selected](https://cloud.githubusercontent.com/assets/2656996/12582230/16fcce18-c43c-11e5-9766-1f6051c72344.png)
![arrow up](https://cloud.githubusercontent.com/assets/2656996/12582229/16fcb676-c43c-11e5-95ce-5324ef101ca6.png)
![arrow up selected](https://cloud.githubusercontent.com/assets/2656996/12582228/16fb293c-c43c-11e5-8265-45cffe84fae8.png)
![eye](https://cloud.githubusercontent.com/assets/2656996/12582227/16fa9044-c43c-11e5-9b31-da140e576e85.png)
![eye selected](https://cloud.githubusercontent.com/assets/2656996/12582231/17044c9c-c43c-11e5-835a-53eae764e41e.png)
![ipad](https://cloud.githubusercontent.com/assets/2656996/12582233/17127ba0-c43c-11e5-932c-4d40c47b18da.png)
![ipad selected](https://cloud.githubusercontent.com/assets/2656996/12582232/17125e0e-c43c-11e5-8091-58dee92472ff.png)
![iphone](https://cloud.githubusercontent.com/assets/2656996/12582236/17194aa2-c43c-11e5-9a8d-befd5e0c3ed8.png)
![iphone selected](https://cloud.githubusercontent.com/assets/2656996/12582234/171569d2-c43c-11e5-99da-cc76de21dd3d.png)
![laptop](https://cloud.githubusercontent.com/assets/2656996/12582235/1715def8-c43c-11e5-85cb-dea3ef8ab0d2.png)
![laptop selected](https://cloud.githubusercontent.com/assets/2656996/12582237/171a74ea-c43c-11e5-85d8-84c01edb54cb.png)
![screen](https://cloud.githubusercontent.com/assets/2656996/12582238/172bc31c-c43c-11e5-8b98-2d058018ddd8.png)
![screen selected](https://cloud.githubusercontent.com/assets/2656996/12582241/17307a92-c43c-11e5-87cf-1269ffed64a7.png)

**Comment by miyconst** [comment]
Good! Thank you!

**Comment by warpech** [comment]
I think we should really use SVG not PNG.

**Comment by andwah** [comment]
Exported the images in  PNG and SVG format, files can be in my dropbox "BlendingEditor" folder.

**Comment by warpech** [comment]
Super, thanks!

Regarding Outline and Fill, they should show the current color choice.

Readability of black text on dark background can be achieved by putting an SVG glow around the text or by using [simple JavaScript color inversion](http://stackoverflow.com/questions/11867545/change-text-color-based-on-brightness-of-the-covered-background-area) ([demo](http://jsfiddle.net/PXJ2C/))

**Comment by tomalec** [comment]
I'd like to note that techically size given in % and px could be as well fixed and flexible. Are we going to expose this feature in the editr, or do we assume that % means flexible and if someone would like to make a tile one third of a size of its 1235wide container, but fixed, he would need to calculate it by his own?

**Comment by miyconst** [comment]
@tomalec I think, the "Grow with parent" button is "flexible" checkbox, so we do expose this feature.

**Comment by tomalec** [comment]
Sorry, my bad, then we probably do not expose `*Adaptive` - grow with siblings (within row/col), but as I'm not yet 100% sure if it will be fully supported in `-table`, maybe we should not bother about it much

**Comment by miyconst** [comment]
- Rename Group and Ungroup to Box and Unbox.
- Add possibility to create empty boxes. The Box button should be a dropdown with items box selection, new line.

**Comment by miyconst** [comment]
I am closing this issue as it is too long and in Launcher repository. Let's use https://github.com/Juicy/juicy-tile-editor/issues for tracking issues and split them into many small items instead of one huge.
