### ISSUE TITLE
Add layout elements in editor

### ISSUE THREAD

**Issue by mattiasmak** [StarcounterPrefabs/Launcher#193]
I see the need to add simple layout elements such as space, line and labels in the editor. This would help to create clean interfaces. 

Now it's like trying to make a large text readable without the ability to add paragraphs. 

So with just a space, line and perhaps labels element would change the editor from night to day for me.

**Comment by Starcounter-Jack** [comment]
I totally agree. We will discuss it on our layout editor meeting tomorrow. Could you attend on our hangout at 11:30.

**Comment by mattiasmak** [comment]
I can attend.

**Comment by warpech** [comment]
@mattiasmak We decided on our own, but I hope this precisely answers your needs!

We will rename the "Group" button to "Box". There will be two additional options available in a dropdown:

1. Empty box (100% x 50px, transparent background)
2. Line (100% x 1px, black background)

The dimensions and colors are just defaults that you can later edit using the regular controls. Technically, an empty box and a line are just empty groups.

Labels is a separate topic: https://github.com/Starcounter/RebelsLounge/issues/14

**Comment by Starcounter-Jack** [comment]
Sorry Mattias. I missed you reply. We are finishing a new editor. We decided to add the possibility to add boxes and lines in the first release.

**Comment by miyconst** [comment]
The new editor has `Empty box` and `Black line` features:

![image](https://cloud.githubusercontent.com/assets/6435556/13171708/85ca9b20-d6f4-11e5-879d-3132d44a652b.png)

Both elements are just empty groups, both can change size and background color.

Closing the issue.
