### ISSUE TITLE
AddFilterToMiddleware problem

### ISSUE THREAD

**Issue by jwillmer** [StarcounterPrefabs/Launcher#194]
If I have an app with the app name ```StorageManagement``` and I create a mapping to my pages with a synonym for the app name like ```stm``` the page will not be displayed in the launcher because the launcher tries to find a app with the name ```stm```.

ProjectName: ```StorageManagement```
```Handle.GET("/stm/example", () => { return new ExamplePage(); });```

Problematic code:
```csharp
 Handle.AddFilterToMiddleware((Request req) => {

                String uri = req.Uri;

                // Checking if we should process this request.
                if (("/" == uri) || (uri.StartsWith("/launcher/", StringComparison.InvariantCultureIgnoreCase)) || (uri.Equals("/launcher", StringComparison.InvariantCultureIgnoreCase))) {
                    return null;
                }

                // Getting application name.
                Int32 splitPoint = uri.Length;
                for (Int32 i = 2; i < uri.Length; i++) {
                    if (uri[i] == '/') {
                        splitPoint = i;
                        break;
                    }
                }

                String appName = uri.Substring(1, splitPoint - 1);

                return WrapInLauncher(req, appName);
            });
```

**Comment by alemoi** [comment]
Thank you for the question! Previously we had an enforcement that all application handlers should start with an appname, for example: "/StorageManagement/menu". Launcher uses this information when wrapping and relies on this. I looked at the code and a lot is based on this assumption, including layouts and workspaces. What do you think @warpech ?

**Comment by alemoi** [comment]
I can possibly add an application name property to Request object identifying the application to which this request belongs.

**Comment by per-samuelsson** [comment]
> I can possibly add an application name property to Request object identifying the application to which this request belongs.

Does that really make sense? Couldn't middleware just access that from `Application.Current.Name`?

**Comment by per-samuelsson** [comment]
> Couldn't middleware just access that from `Application.Current.Name`?

I mean, the idea is that middleware should be isolated on app-level, isn't it? So that MW registered by an application is executed only in that context. No?

**Comment by alemoi** [comment]
> I mean, the idea is that middleware should be isolated on app-level, isn't it? So that MW registered by an application is executed only in that context. No?

The application would be Launcher in this case, since request filter is registered by Launcher app.

**Comment by warpech** [comment]
Thanks for reporting! 

Currently, it is assumed in more than one place that the first segment of the URL is the same as the name of the exe. We have a flag that actually enforces it (see `EnforceURINamespaces` at http://starcounter.io/guides/database/database-configuration/). But we should not actually assume it. The only reason for this should be to make sure that two apps don't accidentally try to register the same URI. 

Otherwise it should be fine to do what you are doing. This can be considered a bug in the code that you posted. @alemoi made commitment to fix this.

**Comment by alemoi** [comment]
I think I fixed this a while ago by introducing `Request.HandlerAppName`, as I remember @chrhol even tested this and its used in Launcher now. Added a sentence in documentation as well.
