### ISSUE TITLE
Remove merged*example

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#197]
@tomalec, can the following files be removed or moved to wiki/gitbook?

https://github.com/StarcounterPrefabs/Launcher/blob/master/mergedHTMLexample.html
https://github.com/StarcounterPrefabs/Launcher/blob/master/mergedJSONexample.json

**Comment by warpech** [comment]
@tomalec bump

**Comment by tomalec** [comment]
I put it into http://starcounter.io/guides/web/partials/#example-2
However I think it's quite long there, do we have any collapsibles in our .io?
