### ISSUE TITLE
Launchpad displays huge icons

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#198]
Since switching to `juicy-tile-table`, Launchpad displays huge icons. 

Testable with Launcher + InvoiceDemo3 (as well as a lot of other apps).

@tomalec can you pls take a look?

![2016-02-17 18_49_06-launcher](https://cloud.githubusercontent.com/assets/566463/13119019/48049a3c-d5a7-11e5-875c-24fccfaf3b0a.png)

**Comment by tomalec** [comment]
It's because Launchpad was not migrated to use `juicy-tile-table`

**Comment by warpech** [comment]
Thanks!
