### ISSUE TITLE
Remove old branches

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/Launcher#199]
@warpech, @tomalec we have a bunch of old branches in Launcher.

I have removed:

- `polymer1` - made by be.
- `juicy-tile-table` - merged by me.

And those left:

- [x] `issue-82` *Updated 2 years ago by @tomalec*
- [ ] `issues/164` *Updated 4 months ago by @tomalec*
- [x] `NoiseApp` *Updated 2 years ago by @tomalec*
- [x] `master-nuget` *Updated 11 months ago by @parherman*
- [ ] `workspace-fix` *Updated 9 months ago by @warpech*
- [x] `master-alexey` *Updated 4 months ago by @alemoi*

Do you think those branches can be removed?

**Comment by warpech** [comment]
My branch `workspace-fix` is still relevant for the issue https://github.com/StarcounterSamples/GoogleSignIn/issues/6. I will try to close the issue and then remove the branch

**Comment by tomalec** [comment]
- `issue-82` - removed, I hope pending `juicy-tile-list` tests na "EVENTUALLY" in successful ones reminds enough to do proper fix for this once https://bugs.chromium.org/p/chromium/issues/detail?id=389566 will be fixed.
- `NoiseApp` - removed, as we no longer support Noise App, and hopefully this workaround is not valid any longer.

**Comment by tomalec** [comment]
I have also removed:
- `puppet-polymer-client` as now it is solved by SysUpgrade app
- `issues/164` as it was merged

**Comment by miyconst** [comment]
`master-nuget` removed, @parherman no longer works for Starcounter.

**Comment by miyconst** [comment]
The `master-alexey` branch was removed by @alemoi, only `issues/164` from @tomalec left to close this issue.

**Comment by tomalec** [comment]
Removed, sorry I thought, I've removed it earlier.
