### ISSUE TITLE
People app does not show up after restart

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#200]
I have quite a peculiar problem. It is 100% reproducible for me.
1. Pull and build Launcher (current master - https://github.com/StarcounterPrefabs/Launcher/commit/7bd6d3e2fda78e18853e71f91bfc665d97c88ff4) and People (current master - https://github.com/StarcounterSamples/People/commit/52e0f76cb1ef461816eea6bfc818ccdc1df96cba)
2. Start Starcounter
3. Clean styles (`DELETE http://localhost:8080/sc/layout?all`)
4. Start Launcher and People using **a batch file**
5. Restart Launcher and People using the batch file.

For some reason it is reproducible only when restarting the app from the batch file, not when starting from Visual Studio. This is the strangest thing about this problem.

This is my batch file:

```
cd c:\www\starcountersamples\launcher
star bin\debug\launcher.exe
cd c:\www\starcountersamples\people
star bin\debug\people.exe
cd c:\www
```

After restart, People app shows empty workspace when loading http://localhost:8080/people/organizations

Interestingly, `juicy-tile-list` prototype shows some weird input in `_defaultSetup`. Screenshot below:

![screen shot 2016-02-19 at 15 17 33](https://cloud.githubusercontent.com/assets/566463/13177846/f62398d2-d71b-11e5-9ca6-e11d62180a5d.png)

**Comment by warpech** [comment]
@miyconst I need your help with this. Please let me know if you can reproduce it.

**Comment by warpech** [comment]
It seems that the namespaces in the merged JSON file are sometimes camelcase (when starting from VS) and sometimes lowercase (when starting from the batch file). This might be the reason.

**Comment by warpech** [comment]
Yeah, I can confirm that this is because `juicy-tile-list` is totally confused by Starcounter not normalizing the executable name from the CLI:

![2016-02-19 15_41_48-launcher2](https://cloud.githubusercontent.com/assets/566463/13178506/7bbc812c-d71f-11e5-93fb-71dd59332b97.png)

![2016-02-19 15_39_45-launcher1](https://cloud.githubusercontent.com/assets/566463/13178437/33c1385e-d71f-11e5-9ddf-624fbe719799.png)

It also appears like that in Administrator:

![screen shot 2016-02-19 at 15 30 11](https://cloud.githubusercontent.com/assets/566463/13178160/b9097b7c-d71d-11e5-8a97-e8ad01e3398b.png)

@chrhol, @per-samuelsson, @andwah - any advice? I believe this is not desired.

**Comment by warpech** [comment]
What adds some spice to the problem is that Launcher 3.0.14 was immune to this problem.

Launcher 3.1.0 (first version that supports `juicy-tile-table`) and `master` are sensitive to it.

@tomalec can you think of any reason for this?

**Comment by warpech** [comment]
I created a related issue in Starcounter: https://github.com/Starcounter/Starcounter/issues/3394

**Comment by per-samuelsson** [comment]
> @chrhol, @per-samuelsson, @andwah - any advice? I believe this is not desired.

I commented on the Starcounter tracker.

**Comment by tomalec** [comment]
I suspect the reason that `juicy-tile-list` is more sensitive to that it uses latest `juicy-tile-list` which shorten, and changed the flow for setup reading, but I'll investigate it deeper.

**Comment by warpech** [comment]
Closing, because it is related to the old layout editor which was phased out.
