### ISSUE TITLE
Unable to select a tile in the layout editor

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#204]
Using current versions of Starcounter develop, Launcher and Products, I am unable to select a tile in simple editor.

I have an idea for a fix and will post it soon. 

The problem originates from the clash of:
- the commit: https://github.com/StarcounterPrefabs/Launcher/commit/8436ed62e8fe7bb62e37990b3517aa27c62d6843
- with the binding from [LauncherTemplate.html#L111](https://github.com/StarcounterPrefabs/Launcher/blob/c71fdd1871290580b1bb1af28ae70600490cb6cf/src/Launcher/wwwroot/Launcher/viewmodels/LauncherTemplate.html#L111)

**Comment by warpech** [comment]
My attempt fixes the JS exception. But still I cannot select a single tile in the layout editor.

I cannot select deeper than this: 

<img width="1436" alt="screen shot 2016-02-29 at 11 51 19" src="https://cloud.githubusercontent.com/assets/566463/13392442/d326a3c6-deda-11e5-9b43-d6dcfcfd5217.png">

@miyconst can you give it a try?

Using Starcounter 2.1.1316 and current `master` branches of Launcher and Products.

**Comment by miyconst** [comment]
This is due to old setup which was applied for `juicy-tile-grid`, not table.

@warpech can you confirm that resetting styles works for you?

**Comment by warpech** [comment]
Resetting styles fixes the problem. I don't like that it is needed. @tomalec any idea why resetting styles is needed?

**Comment by tomalec** [comment]
Wow, it looks strange, for mee it seems not related to the setup. Even if I replace the setup in source tab with same one, it works.

**Comment by tomalec** [comment]
@miyconst Does editor support loose groups? I think that is the reason, as `j-t-t` renders things right, and editor works fine besides the fact it does not highlight loose group - probably because there is no single tile to select, we need to buiild highlight rectangle manually.

And the lack of double click effect for nested tiles is probably also because of lack of support in the editor.

**Comment by miyconst** [comment]
Thanks for noting this out. The editor supported it some time ago, but was not tested for long time. I will check and fix it.

**Comment by miyconst** [comment]
Moved the issue to `juicy-tile-editor`: https://github.com/Juicy/juicy-tile-editor/issues/134.
