### ISSUE TITLE
Cannot morph back to launchpad

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#205]
If the page was loaded in a workspace, Launchpad does not appear.

Steps to reproduce:

1. Start Launcher and Products
2. Go to localhost:8080/products
3. Click on the "Home" icon
4. Check if you can see Launchpad icons

See:

![after](https://cloud.githubusercontent.com/assets/566463/13948102/8aa29056-f01e-11e5-8e11-d1e2d473c210.gif)

Notice that this was changed in commit https://github.com/StarcounterPrefabs/Launcher/commit/366d6017c40219929971ac1e917d0e96df4086fa (which was a fix for https://github.com/StarcounterPrefabs/Launcher/issues/198). It worked before, but the icons had incorrect size:

![before](https://cloud.githubusercontent.com/assets/566463/13948108/8efcf448-f01e-11e5-9d06-1e2f96610a2f.gif)

@tomalec can you take a look?

**Comment by tomalec** [comment]
It seems launcher-launchpad was not updated once we switched from layout as object to layout as string. https://github.com/StarcounterPrefabs/launcher-include/commit/d4f22311d6932fa3284e4090f3e26e65838192c3
https://github.com/StarcounterPrefabs/launcher-include/issues/9
https://github.com/Juicy/juicy-tile-editor/issues/127

**Comment by warpech** [comment]
The fix doesn't seem to work for me (using Starcounter 2.1.1527 and Chrome). Could you please check again?

Not only Launchpad is affected but also the Settings page.

**Comment by tomalec** [comment]
I was using older Starcounter, I'll check that

**Comment by warpech** [comment]
Now it works OK for me again. Sorry for bothering you, this must have been something on my side.

Tested with Starcounter 2.1.1527 and Launcher `master` in Chrome, FF, Edge.
