### ISSUE TITLE
How to: Settings

### ISSUE THREAD

**Issue by andwah** [StarcounterPrefabs/Launcher#209]
Running apps:  Launcher v3.1.6, Sign-In 3.1.12 and [Warehouse](https://github.com/Starcounter/Warehouse)

When i click the "Gear" icon my settings is not shown:

![image](https://cloud.githubusercontent.com/assets/2656996/14101943/0c53c362-f598-11e5-9264-215d4eb9c132.png)

If i refresh the page it works:

![image](https://cloud.githubusercontent.com/assets/2656996/14101963/286dac16-f598-11e5-95df-e3a375ea19d3.png)

**Comment by andwah** [comment]
And when i "sign in" i get this red text:

![image](https://cloud.githubusercontent.com/assets/2656996/14102051/aebefdb0-f598-11e5-940f-d3608859a301.png)

**Comment by andwah** [comment]
And after clicking the "Gear" a couple of times i get this result.

![image](https://cloud.githubusercontent.com/assets/2656996/14102094/e45e7a0e-f598-11e5-8e6d-c79efb73e8d6.png)

**Comment by warpech** [comment]
What is the Starcounter and Launcher version that you are using? These problems were fixed last week.

**Comment by andwah** [comment]
Launcher v3.1.6 and im using a local build of starcounter (over a week old).

**Comment by warpech** [comment]
This is fixed in Launcher nightly. Please reopen if you still experience it after upgrading. Thanks!
