### ISSUE TITLE
Replace bootstrap theme with something without shadows

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/Launcher#210]
The css shadows are not included in the element dimension and causes issues inside `juicy-tile-table` with default styles:

![image](https://cloud.githubusercontent.com/assets/6435556/14104186/0e655754-f5a4-11e5-882e-59f4e2786f10.png)

Possible replacements:

### Cosmo

https://bootswatch.com/cosmo/

![image](https://cloud.githubusercontent.com/assets/6435556/14104302/cd6a7af8-f5a4-11e5-94dc-27c40793240f.png)

### Yeti

https://bootswatch.com/yeti/

![image](https://cloud.githubusercontent.com/assets/6435556/14104418/675de64a-f5a5-11e5-8c93-21a56fef57da.png)

More themes are available there: https://bootswatch.com/.

cc @warpech, @andwah, @tomalec

**Comment by warpech** [comment]
Yeti theme has a glow on input focus. Doesn't it cause the scrollbars to appear?

<img width="440" alt="screen shot 2016-03-29 at 12 19 26" src="https://cloud.githubusercontent.com/assets/566463/14104917/81b66e2e-f5a8-11e5-8898-194ef2c4a173.png">

**Comment by miyconst** [comment]
Yes, it has outline for inputs, but this does not cause scroll bars and without the outline it still looks good. So, it can be removed with custom style overwrite.

![image](https://cloud.githubusercontent.com/assets/6435556/14106321/a05c2924-f5b0-11e5-9ebc-78c033cf96cf.png)

**Comment by miyconst** [comment]
The **Cosmo** theme also has those shadows.

**Comment by warpech** [comment]
> Yes, it has outline for inputs, but this does not cause scroll bars and without the outline it still looks good. 

How come it does not cause scrollbars? Doesn't box-shadow always trigger scrollbars?

**Comment by miyconst** [comment]
It is not `box-shadow`, it is `outline`.

**Comment by warpech** [comment]
In Yeti, it is definitely `box-shadow`:

<img width="1411" alt="screen shot 2016-03-29 at 17 53 46" src="https://cloud.githubusercontent.com/assets/566463/14114430/3848526e-f5d7-11e5-9f1f-62ba2779612e.png">

But maybe I am puzzled about this, and actually it is NOT `box-shadow` that causes scrollbars?

**Comment by miyconst** [comment]
Looks like we mixed up two issues.

- The `box-shadow` property is not included in the box dimension, and being cut of by Shadow DOM container of juicy-tile.
- The tiles with `display: inline;` causes scroll bar. 
- The `margin-bottom` property also causes scroll bar, often with `1px` in size.

**Comment by tomalec** [comment]
As https://github.com/Juicy/juicy-tile-table/issues/4 is fixed, and `juicy-tile-table` supports shadows for tiles gently. Do we still need this one?

**Comment by miyconst** [comment]
@tomalec thank you for the fix, I don't think we need to change the theme right now. Closing the issue.
