### ISSUE TITLE
Remove workspaces

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#211]
As discussed with @miyconst, current implementation of workspaces does not give any clear benefits and has some disadvantages:

1. It still requires a HTTP request to morph between workspaces, causing a workspace to rebuild each time it is switched
2. There is a limitation of one workspace per app, which doesn't make any sense (https://github.com/StarcounterPrefabs/Launcher/issues/161)
3. Workspaces cause a lot of work to maintain bindings for data that is not currently displayed (https://github.com/StarcounterPrefabs/Launcher/issues/160)

A solution to the above problems is to remove the concept of workspaces. We might implement it again some day, but taking all of the above issues into consideration.

Workspaces are still a cool idea for future (to have side-by-side layouts for example), but this is months of work to make it proper.

**Comment by malx122** [comment]
Actually workspaces is really good if used correctly. Our implementation when we had only one app (integrated launcher-apps) was more or less perfect since it "cached" apps in the background and disabled auti bindings while not displayed. For more intensive client apps like organizer (gantt) and actionboards this improves speeds when switching and we need that speed.

**Comment by malx122** [comment]
We also need it to not loose client data when switching back and forth. (You can't store everything in the URL)

**Comment by malx122** [comment]
So removing workspaces would cause our applications not to work as it is designed to at the moment.

**Comment by miyconst** [comment]
@malx122 removing workspaces does not mean removing view-state.

If your application saves JSON view-model in `Session.Data` then it will stay there as long as session lives.

The custom WebComponents are cached on browser level and are not imported twice. So, if a component was loaded with `<link rel="import" href="/sys/tunity/tunity-gunt" />` on a page load, then it won't be loaded again when you navigate back to the page.

What exactly would break your apps? I would like to keep backward compatibility and don't face you against another major rework.

**Comment by malx122** [comment]
That the application saves the Json view-model is a minor detail. Just a few nonexpensive classes and all database calls that could be expensive is redone all the times anyways...

Loading and parsing webcomponents is expensive (especially on non-chrome browsers), but also not the issue I'm talking about.

Creating webcomponents can be very expensive and that is not cached if you remove the workspaces. A part from that, client specific data as scrollbar positions, open/closed aktivities in the gantt e.t.c. will be lost if you navigate from the gantt.
We have customers that only use actionboard, no problem for them,
We have customers that only use gantt, no problem for them either.
But there is also the use case that a person use the gantt to navigate and look inte different actionboards. And to need to renavigate the gantt every time you have switched to an actionboard and go back is not ok for them.

**Comment by malx122** [comment]
I do agree that the workspaces does not work well for the moment. But I'm quite sure there is some better solutions than scrap them. I will think about a solution tonight :)

**Comment by warpech** [comment]
> A part from that, client specific data as scrollbar positions, open/closed aktivities in the gantt e.t.c. will be lost if you navigate from the gantt.

This is the penalty of having presentation logic, which should be kept to minimum. Thanks for bringing that point up! Of course some things (like scrollbar positions) cannot be delegated to server at all.

> Creating webcomponents can be very expensive and that is not cached if you remove the workspaces.

Actually since my recent change https://github.com/StarcounterPrefabs/Launcher/commit/1c1aec7d03e6d567ecc89f4dfa666bf0156e3eac inactive workspaces are removed from DOM anyway. Did you experience any performance penalties? I didn't think of this use case and I think that I can restore it.

We went half way to remove workspaces already (with https://github.com/StarcounterPrefabs/Launcher/commit/1c1aec7d03e6d567ecc89f4dfa666bf0156e3eac), so now we can either bring them back (and make sure they are actually useful and performant) or remove them completely. Basically, the benefits need to outweigh the issues. I thought @malx122 will be on the issues side, but seems not! Please share any more thoughts.

**Comment by malx122** [comment]
Since we have our own version of launcher I havnt merged and tested #1c1aec7 yet. And now that I read about it I'm guessing that merge that one in is not an option either... That will most likely destroy all client data as well?

**Comment by warpech** [comment]
Yes, switching workspaces will destroy the presentation data of Polymer elements, because of removing them from DOM.

> Our implementation when we had only one app (integrated launcher-apps) was more or less perfect since it "cached" apps in the background and disabled auti bindings while not displayed

How did you achieve disabling auto bindings with inactive workspaces?

**Comment by malx122** [comment]
Our "workspaces" was handled both at the server level and at the client level. So one "app" could have not just one but multiple workspaces and decide when to create, when to inactivate and when to destroy them.

**Comment by malx122** [comment]
The server part of that solution is actually still active in our apps. So one app could have multiple "workspace" inside its Launcher workspace. But its not used. (I was actually thinking of inactivate the auto bindings in our workspaces based on some static list in the common dll since it is shared between our apps but I havnt done it yet)

**Comment by malx122** [comment]
Think I have a solution that would solve some of the problems with the launcher and apps, we can talk about it tomorrow after lunch.

**Comment by warpech** [comment]
Fair enough! Closing this issue and moving discussion to #214.

A feature of turning off workspaces can still be added. Launcher with "single workspace" setting set to ON would just remove previous workspace from the array in C#. But this is a matter for a separate issue.
