### ISSUE TITLE
Conditionally skip wrapping of pages in Launcher

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#212]
Currently, Launcher wraps all pages. It should only wrap pages that want to be wrapped.

The current workaround is to use `SkipMiddlewareFilters`/`SkipRequestFilters` on handlers that should not be wrapped in Launcher. But this also removes automatic sign in by SignIn app.

The solution is to only wrap in Launcher pages that have Json property `Html` (`text/html` representation).

Long term solution should be even more control with conditional `Use()` middleware.

**Comment by warpech** [comment]
The solution is to add a Settings page with Regular Expression for excluded app URLs

@aloscha this is what your are doing on branch: https://github.com/StarcounterPrefabs/Launcher/blob/Bypass_launcher_for_apps

**Comment by warpech** [comment]
Fix in progress in PR: https://github.com/StarcounterPrefabs/Launcher/pull/239

**Comment by aloscha** [comment]
Fiexed on master.
