### ISSUE TITLE
Restore workspaces

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#214]
Follow up to https://github.com/StarcounterPrefabs/Launcher/issues/211

Changes made after Launcher 3.1.6 caused workspaces to be reloaded when switching from one workspace to another. This is causing reset of presentation state, which is unwelcome by applications developer.

Let's bring back the functionality that existed in Starcounter 2.1.177 + Launcher 3.1.6, which kept the initial state of the workspace when switching back to it. 

There are two parts of this task (HTML and C#). I will make the HTML part

**Comment by warpech** [comment]
Later, I will also add Selenium integration tests for this

**Comment by warpech** [comment]
Work is done on a branch: https://github.com/StarcounterPrefabs/Launcher/tree/restore_workspaces

I think that HTML part is done, but there is still come problem with the C# part. Every `HTTP GET` with `Accept: application/json-patch+json` request causes a `replace` operation on the whole workspace. 

The below gif illustrates the problem (see until the end, when the patch is presented). The red counter on the top of the page should say "Launcher has created 1 workspaces" through the whole gif.

@chrhol I need your help with this. Can you please take a look?

![bug](https://cloud.githubusercontent.com/assets/566463/14137362/cadbc4c2-f667-11e5-8966-1c49459df1f9.gif)

**Comment by chrhol** [comment]
I will take a look. I wonder what have changed from the old version? If a workspace already exists it's reused in the Launcher so the problem must be somewhere inside Starcounter.

**Comment by chrhol** [comment]
Found the reason. The internal handling of newly added siblings is to mark the main object (in this case the workspace json) as replaced and send the whole json. 

This worked before due to that no siblings were changed, but after we added the callback a new sibling is always added on a merge.

I will add an issue in Starcounter to fix this somehow. We need to keep track of which siblings we had before the merge and only send what's been changed.

**Comment by chrhol** [comment]
Just a note on this: On the server everything is reused, the replace happens on the client-side

**Comment by chrhol** [comment]
https://github.com/Starcounter/Starcounter/issues/3465

**Comment by warpech** [comment]
Great that you've found the problem. Looking forward the solution.

**Comment by warpech** [comment]
The fix is now up and running in Launcher `master` branch, including [tests](https://github.com/StarcounterPrefabs/Launcher/blob/master/test.bat).

@malx122 now workspaces again support preserving of presentation state (scrollbars, etc) and no longer rely on URL parsing to find the current workspace.
