### ISSUE TITLE
Freeze bindings of inactive workspaces

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#215]
As @malx122 suggests in https://github.com/StarcounterPrefabs/Launcher/issues/211, inactive workspaces can be frozen from bindings by using `AutoRefreshBoundProperties` property of `Json`. 

Anyone has something against this feature? It can be made configurable in Launcher settings.

**Comment by warpech** [comment]
This may be hard, but let's see how it goes for you @joozek78!

In Launcher solution, there is a Launcher app are two helper test projects (Launcher_AcceptanceHelperOne & Launcher_AcceptanceHelperTwo).

Start Launcher and Launcher_AcceptanceHelperOne and Launcher_AcceptanceHelperTwo. You should see these two helper apps in the left menu. When you visit them in the menu, this will create a workspace for them (visible in starcounter debug aid in `Workspaces` array).

Currently, these two helper apps don't share any data. But you can add a reference to `Simplified Data Model` in both of the helper apps. This will allow you to use the same data classes in both apps. 

In one of the apps, create an instance of `Simplified.Ring1.Something` with `Name = "AutoRefreshBoundPropertiesTest"` (if it doesn't exist) and bind it to a property in JSON. In the other app do the same. Show it in UI as a text input.

Now you have two apps that show a property bound to the same instance of an object. Typing in the input field of the first app will update the other app, which runs in a separate workspace.

The task of this issue is to set `AutoRefreshBoundProperties = False` in the correct place in `Launcher` app. After that, making change in one app will not update the workspace of another app.

Please try to go as far as possible with impletenting this issue and a test for it. @chrhol can help you with `Json`, @aloscha can help you with tests.

**Comment by warpech** [comment]
The solution is missing tests. The test should directly bind to PuppetJs's callback `onRemoteChange` to check what patches are (not) received from the server.

**Comment by joozek78** [comment]
https://github.com/StarcounterPrefabs/Launcher/pull/241
