### ISSUE TITLE
Add Cookie usage popup

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/Launcher#217]
By EU law any website using cookies should tell about it.

**Comment by miyconst** [comment]
Reported by @malx122.

**Comment by malx122** [comment]
It actually says that user need to actively accept the use of cookies.

**Comment by miyconst** [comment]
The popup has been added:

![image](https://cloud.githubusercontent.com/assets/6435556/15739087/b389fe96-28ae-11e6-91ea-d5cca77babf9.png)

@warpech, @dan31 any changes to the words? Right now it is:

>We use cookies to enhance your experience with this application.

**Comment by warpech** [comment]
> It actually says that user need to actively accept the use of cookies.

Are you sure about this? See: https://econsultancy.com/blog/63118-17-useful-examples-of-eu-cookie-law-compliance/

> @warpech, @dan31 any changes to the words? Right now it is:

> > We use cookies to enhance your experience with this application.

I would actually change it to: "This application uses cookies to enhance your experience. By continuing to use this website you accept the [cookie policy]."

And the cookie policy should be a link to a (configurable) text page.

I think that this should be configurable on the Settings page with two options:

- Show cookie consent (checkbox)
- Cookie consent text (input)

Settings page structure can be copied from Images app.

On a sidenote, does Launcher use persistent cookies? I guess only SignIn and UsageTracker apps uses persistent cookies right now?

**Comment by warpech** [comment]
Does Launcher actually use persistent cookies? I guess only SignIn and UsageTracker apps uses persistent cookies right now?

I think that "Cookie Consent" would be a great separate **micro app** with the following configurable options on the Settings page (which can be cloned from the Images app):

- Show cookie consent (checkbox)
- Cookie consent short text (textarea, with HTML allowed). The short text can contain a link to the long text full page.
- Cookie consent long text (textarea, with HTML allowed)

> @malx122:
> It actually says that user need to actively accept the use of cookies.

Are you sure about this? See: https://econsultancy.com/blog/63118-17-useful-examples-of-eu-cookie-law-compliance/

> @miyconst:
> @warpech, @dan31 any changes to the words? 

I would actually change it to: `This application uses cookies to enhance your experience. By continuing to use this website you accept the <a href="/cookieconsent">cookie policy</a>.`

**Comment by miyconst** [comment]
>I think that "Cookie Consent" would be a great separate micro app with the following configurable options on the Settings page (which can be cloned from the Images app):

Totally agree. I do that.

**Comment by miyconst** [comment]
@malx122 I have made another app [CookieConsent](https://github.com/StarcounterPrefabs/CookieConsent) please take a look and let me know whether it's what you needed.

**Comment by warpech** [comment]
@miyconst can this be closed?

**Comment by miyconst** [comment]
I think so, but @malx122 should confirm.

**Comment by warpech** [comment]
@miyconst can the following line be removed from Launcher?

https://github.com/StarcounterPrefabs/Launcher/blob/bfaee5b665e4c4081b7bca0c28b254c5e3fa62e1/src/Launcher/wwwroot/Launcher/css/style.css#L285

**Comment by warpech** [comment]
Ping

**Comment by miyconst** [comment]
@warpech sorry for missing your question. It is removed now.

**Comment by warpech** [comment]
Thank you. I think this can be closed now

**Comment by warpech** [comment]
@miyconst when you make changes to a `master` branch, and a `develop` branch exists as well, please merge `master` to `develop` afterwards.
