### ISSUE TITLE
Removed paper-dialog, possibly other dependencies?

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#218]
@tomalec, it seems that in your commit  https://github.com/StarcounterPrefabs/Launcher/commit/6606846cd2983afd1c8b1325b31ecb30ffb8c999 you have removed some of the libraries that were actually used (at least `paper-dialog`). 

Could you please check and restore what's needed?

Discovered today with @ubbeK 

Screenshot: 

![screen shot 2016-04-06 at 11 32 57](https://cloud.githubusercontent.com/assets/566463/14318515/74a04bd6-fc0d-11e5-8b0b-9fee3e6bd3de.png)

**Comment by tomalec** [comment]
Ok, I thought those are some kind of legacy code, as were not mentioned in `bower.json`, an I just did regular bower cleanup.

**Comment by tomalec** [comment]
I have reverted my changes, to make code work, and created [bower cleanup issue](https://github.com/StarcounterPrefabs/Launcher/issues/219) to make it later, as I would like to focus now on composer, and predefined layouts

**Comment by warpech** [comment]
Lesson to everyone: When putting client side packages to `/sys/`, always save it in `bower.json`
