### ISSUE TITLE
Clean bower.json

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Launcher#219]
As it occurred at https://github.com/StarcounterPrefabs/Launcher/issues/218
We have some dependencies that are not saved in `bower.json`

We need to investigate the code and find those, to make `bower installs`, `update`, `prune` work consistently.

**Comment by warpech** [comment]
@miyconst could you please take this?

**Comment by tomalec** [comment]
I did actually some clean up recently in juicy-composition branch, so you can double check it there.

**Comment by warpech** [comment]
Seems fixed on `develop` branch
