### ISSUE TITLE
Double clicking on juicy-tile-table does not select it in the editor

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Launcher#220]
@malx122 reported that in Tunity App when the partial (and `juicy-tile-table`) is nested a little bit deeper, and takes the whole workspace area, when the editor is open double clicking in this area makes no effect.

@miyconst, Could you take a look?

**Comment by tomalec** [comment]
It seems that we are finally able to click into, but we had to click many, many times.
Maybe we have an idea how to improve the experience of clicking into the tiles?

What about leaf to root direction?

**Comment by miyconst** [comment]
I thought of automatically scoping into a tile if it's a single tile on a level, but this rises a question, how to edit properties of this single tile.

**Comment by tomalec** [comment]
My proposition:
1. Select top most (leaf) node,
2. If designer would like to go level up, he/she can use breadcrumbs/keyboard shortcut, some 'level-up' button

I think usually you would like to style individual elements, not the huge blocks, that covers entire page.

**Comment by miyconst** [comment]
Sounds good to me. I will implement such behavior, next week probably.

**Comment by miyconst** [comment]
Closing as no longer relevant.
