### ISSUE TITLE
Remove `launcher-main`

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#225]
Launcher contains a custom element [`launcher-main`](https://github.com/StarcounterPrefabs/Launcher/blob/master/src/Launcher/wwwroot/Launcher/elements/launcher-layout/launcher-main.html) that extends `body`. I think there is no benefit in it. There are drawback like code obfuscation and performance penalty.

I think that this custom element should be removed and the code should be inlined in `LauncherTemplate.html`.

**Comment by tomalec** [comment]
I have created with "Everything is an element" attitude, to separate our styling div soup, from meaningful content of Launcher and apps.

But, you are probably right that this is just 3 `div`s and 25 lines of CSS - not much to hide - for a cost of HTML import, shadow DOM and custom element (especially polyfilled).


I just dream of a perfect Starcounter suite markup  :heart_eyes:
```html
<link rel="import" href="/just/few/imports.html"/>
<body is="launcher-body">
   <launcher-toolbar>Home, search, settings</  >
   <launcher-workspace>
      <AppA-element>with some content</  >
      <Appb-element>with another content</  >
    </  >
</body>
```
with almost no `<div>`s :godmode:

**Comment by warpech** [comment]
For me, it only makes sense to use Custom Elements for custom presentation logic. 

If we use Custom Elements to encapsulate styles (like `launcher-main.html` does), this just brings questions: "Do I have to do it this way?", "How do I style customize it?", "Am I allowed to touch `launcher-main.html`"?

**Comment by tomalec** [comment]
:+1: Thx, now I feel 100% convinced to do it :)

**Comment by warpech** [comment]
Done
