### ISSUE TITLE
Launcher does not react on Html property change of a partial

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/Launcher#227]
I have an app which changes Html of a partial. The change is not reflected in both merged `Html` property and `Launcher.MergedHtml`.

![image](https://cloud.githubusercontent.com/assets/6435556/14739945/51a422da-088b-11e6-8037-d27842e9ae8b.png)

cc @warpech, @chrhol

**Comment by warpech** [comment]
I need to pass it on to @chrhol, because that looks like a Starcounter issue (`Html` and `JsonResponseMerger.RegisterMergeCallback`). Could you post a link to code that reproduces the problem?

**Comment by miyconst** [comment]
We should no longer rely on `Launcher.MergedHtml` property. Closing this issue.
