### ISSUE TITLE
Launcher uses imported-template to display User section

### ISSUE THREAD

**Issue by miyconst** [StarcounterPrefabs/Launcher#228]
With the latest changes in html merger we are no longer able to use `imported-template` for showing merged partials.

We should do one of:

- Improve `imported-template`.
- Replace `imported-template` with `starcounter-include`.
 - Add possibility to provide default first break point value.
 - Add possibility to apply layout styles in the Launcher's header.

cc @warpech, @tomalec

**Comment by tomalec** [comment]
> we are no longer able to use imported-template for showing merged partials.

You mean that you are not able to provide URL for merged partial to `imported-template`, don't you?

> - Improve imported-template.

If it means moving out `htmlmerger` URL magic there, I vote for no.

> - Replace imported-template with starcounter-include.

For me it's not the worst thing to choose. However, then we will disable the possibility to opt-out from Launcher/Starcounter layouts for partials

>-  Add possibility to provide default first break point value.
- Add possibility to apply layout styles in the Launcher's header.

Could you elaborate a bit more?

**Comment by miyconst** [comment]
>Add possibility to provide default first break point value.

Right now `juicy-tile-table` got the first break point value as the window size. Which causes terrible design glitches when it's inside the "User" section which usually is not bigger than `300px`.

>Add possibility to apply layout styles in the Launcher's header.

Right now it's not possible to use Layout editor to edit `juicy-tile-table` inside the header. I remember, at some point it was decided to enable the editor for content only.

**Comment by tomalec** [comment]
1. Add possibility to provide default first break point value.

    How would like to set it up?

2. Add possibility to apply layout styles in the Launcher's header.

   By the "header" do you mean Launchers top bar? If so I see no reason for blocking it. @warpech any thoughts?

**Comment by miyconst** [comment]
>How would like to set it up?

For example:

```html
<starcounter-include juicy-style="width: 300px;" partial="{{model.User}}"></starcounter-include>
```

**Comment by miyconst** [comment]
>By the "header" do you mean Launchers top bar? If so I see no reason for blocking it.

Yes, and I also don't see a reason for blocking it, just another piece of work.

**Comment by tomalec** [comment]
1. I like the concept of providing hints in markup, but the problem with you proposition is when it 

  `<starcounter-include>` is also a tile
 ```html
<juicy-tile-*> <!-- or just root of a partial -->
    <starcounter-include juicy-style="width: 300px;" partial="{{model.User}}"></starcounter-include>
</juicy-tile-*>
```
then `juicy-style` stands for `width` for the tile. Not for the "first breakpoint of `juicy-tile-table` inside `<starcounter-include>` (if any)"

2. :+1:

**Comment by miyconst** [comment]
1. I know, but I don't have any better option, and the issue should be solved somehow. Why the value can't mean both? The width of the tile, and the first break point for the `juicy-tile-list` inside?

**Comment by tomalec** [comment]
>  Why the value can't mean both? The width of the tile, and the first break point for the juicy-tile-list inside?

The width of the tile could be `50%` but first break point could not. Moreover, in desired solution we will have multiple breakpoints per element.

You said 
> Right now juicy-tile-table got the first break point value as the window size.

Is it really **window** size? At the beginning it was **element** size, which should make more sense if no setup given. Plus if you have set `juicy-style` or size of enclosing element like 
```
<element-on-partials-root juicy-style="width: 400px">
  <div style="width: 50%">
    <starcounter-include></starcounter-include>
  </div>
</element-on-partials-root>
```
then the `<juicy-tile-*>` inside `<starcounter-include>` should receive `200` as first breakpoint

**Comment by miyconst** [comment]
Okay, I double check that, but it didn't work for me that way.

**Comment by tomalec** [comment]
If it does not work that way, it's a `<juicy-tile-*>` bug

**Comment by tomalec** [comment]
I believe, at https://github.com/StarcounterPrefabs/Launcher/commit/16f4415cd463db9420e857b7dd1a3b1c690e5c74 I have provided a fix for OP.

As I replied https://github.com/StarcounterPrefabs/Launcher/issues/228#issuecomment-217464747 the problem was to " provide URL for merged partial to `imported-template`".

In Launcher we are sure, that Launcher is running, so that there is `partial.Launcher.MergedHtml` with URL that we need.

So, I think OP is solved.

However in meantime many side issues popped out:

1. Should app dev be able to use `imported-template` that will handle merged partials?
2. Add possibility to provide default first break point value.
3. Add possibility to apply layout styles (use Launcher's `starcounter-include` with `juicy-tile-*`) in the Launcher's
 1. header.
 2. menu

@miyconst, @warpech Do we want to address those here, or close this issue, and track any of them in separate issue?

**Comment by miyconst** [comment]
@tomalec thank you for the fix, let's close this issue.

>In Launcher we are sure, that Launcher is running, so that there is `partial.Launcher.MergedHtml` with URL that we need.

In MM we don't need the layout info, and `<starcounter-include>` can be used without issues.
