### ISSUE TITLE
Fix or remove ::shadow styles

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#235]
As discovered by @tomalec in https://github.com/Starcounter/Starcounter/issues/3562#issuecomment-231155935:

> This seem to break existing ::shadow CSS selectors in 
https://github.com/StarcounterPrefabs/Launcher/blob/2886d9b746917eb953a051601d40178f5077085e/src/Launcher/wwwroot/Launcher/css/style.css

I removed the styles at  https://github.com/StarcounterPrefabs/Launcher/blob/2886d9b746917eb953a051601d40178f5077085e/src/Launcher/wwwroot/Launcher/css/style.css#L263-L269, because that was not the most beautiful effect anyway.

I try to understand the reason for using the other `::shadow` CSS selectors. It seems that these styles are not used anywhere:

1. https://github.com/StarcounterPrefabs/Launcher/blob/2886d9b746917eb953a051601d40178f5077085e/src/Launcher/wwwroot/Launcher/css/style.css#L84-L98
2. https://github.com/StarcounterPrefabs/Launcher/blob/2886d9b746917eb953a051601d40178f5077085e/src/Launcher/wwwroot/Launcher/css/style.css#L245-L247

@miyconst can you confirm if these can be removed?

**Comment by miyconst** [comment]
It looks like those are very old styles introduced by @tomalec in this commit: https://github.com/StarcounterPrefabs/Launcher/blame/d38f5b3f20475866b51f4655cde9f6389bf09df3/wwwroot/Launcher/css/launcher-main.css.

I also can't find what are they for. The styles removed.

**Comment by tomalec** [comment]
If I recall correctly it was to style paper checkboxes and radios in Filter view, which no longer exists

**Comment by warpech** [comment]
Thanks!
