### ISSUE TITLE
Pages not changing in Latest Launcher build

### ISSUE THREAD

**Issue by atifwaqar** [StarcounterPrefabs/Launcher#246]
SC Version 2.2.2.3422
Launcher Version with bug : 5.0.0 (Oct 7, 2016 2:40:59 AM)
Launcher Version without bug : 5.0.0-develop.1 (Sep 12, 2016 1:01:31 PM)

Behavior with Launcher V-5.0.0 (Oct 7, 2016 2:40:59 AM)
Step 1 (open dashboard) : 
![image](https://cloud.githubusercontent.com/assets/4388707/19679381/d4ce9d54-9aa1-11e6-8ca6-fedff777be59.png)

Step 2 (Clink on any page link from left panel) :
![image](https://cloud.githubusercontent.com/assets/4388707/19679396/dc6cc6bc-9aa1-11e6-9d27-9d437b1c6748.png)

Issue, the page is still the same, only Url is changed in Address bar.

Behavior with Launcher V-5.0.0-develop.1 (Sep 12, 2016 1:01:31 PM)
Step 1(Open Dashboard) :
![image](https://cloud.githubusercontent.com/assets/4388707/19679488/3a071b9c-9aa2-11e6-9abc-fc6137f2e90f.png)

Step 2 (Clink on any page link from left panel) :
![image](https://cloud.githubusercontent.com/assets/4388707/19679494/44c94014-9aa2-11e6-9beb-727cbea56687.png)

Works fine with this Launcher version. The page and url both are changing now.

**Comment by warpech** [comment]
@atifwaqar is this still a problem in Launcher 6.0.0? I believe not?

**Comment by atifwaqar** [comment]
I haven't tested this yet, will do it today hopefully. and update this thread accordingly.
