### ISSUE TITLE
Release a version of Launcher into the new Warehouse

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#249]
Release a version of Launcher into the new Warehouse

- [x] Check if Launcher `develop` is safe to merge to `master` (using TeamCity - [instructions](https://github.com/StarcounterPrefabs/Guidelines/blob/master/continuous_integration.md))
- [x] Merge Launcher `develop` to `master`
- [x] Package the version Launcher 5.0.1 using `starpack`
 1. if your installation of Starcounter doesn't have `starpack`, copy files from https://www.dropbox.com/sh/uq4eacrhm3fh0sn/AAA2vhuJL0cauTJx_ltha4MBa?dl=0 to `c:\program files\starcounter`
 2. primitive instruction for providing the version number is here: https://github.com/Starcounter/Warehouse/issues/102
 3. after changing AssemblyInfo, you need to rebuild the project. Make sure you are building with Starcounter stable.
 4. now you can call `starpack -p` to create the ZIP
- [x] Upload to the new Warehouse
- [ ] Commit changed package metadata files to develop, then merge to master
   - Marcin to check what files need to be commited.

**Comment by warpech** [comment]
I will check if all these steps are performable.

Step 1 is performable. @Mackiovello can you please perform that?
I will check if Step 3 is performable

**Comment by warpech** [comment]
Checkbox 3 is performable.

I am stuck at Checkbox 4 with the error:

> Launcher-5.0.1.zip, Uploaded version namespace (Launcher.Launcher) does not match application namespace (StarcounterSamples.Launcher).

Checking with @andwah

**Comment by andwah** [comment]
the `Launcher` was was previous uploaded with a different namespace `Launcher.Launcher`  and now you are trying to upload a new `Launcher` with a new namespace `StarcounterSamples.Launche`  in "old" `Launcher`

**Comment by warpech** [comment]
but how do I control that? how did you upload "Launcher.Launcher"?

**Comment by andwah** [comment]
you can overide the "namespace" by adding this line in your project

`AssemblyInfo.cs`

[assembly: AssemblyMetadata("ID", "Launcher.Launcher")]

**Comment by andwah** [comment]
BTW im thinking of renaming the property "namespace" to simple "ID" in a future version of the warehouse

**Comment by andwah** [comment]
sorry it should be

`[assembly: AssemblyMetadata("ID", "StarcounterSamples.Launcher")]`

**Comment by warpech** [comment]
> sorry it should be
> [assembly: AssemblyMetadata("ID", "StarcounterSamples.Launcher")]

I confirm that this works, thanks!

Checkbox 4 is now performable.

Checkbox 5 of course, too. Now giving the driving wheel to @Mackiovello to actually perform all these steps.

I will crete a Warehouse user account for @Mackiovello.

**Comment by warpech** [comment]
> I will create a Warehouse user account for @Mackiovello.

It seems that I can't... @andwah can you do that?

**Comment by andwah** [comment]
i will try. but signin, registration and useradmin app is not working together.. need to to find the right old version of the apps to get it working. i will try

**Comment by andwah** [comment]
done.

**Comment by warpech** [comment]
I am reinvestigating Checkbox 5.

**Comment by Mackiovello** [comment]
Launcher is released
