### ISSUE TITLE
Replace Self.GET to mapping URIs with handler URIs

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#254]
In many places Launcher is using Self.GET to a mapping URI - which will not be supported in future versions of Starcounter. 

Launcher needs to have handlers for every mappable URI. Perform Self.GET to these handlers, and use `UriMapping.Map` to provide the mapping URI.

Related: https://github.com/Starcounter/Starcounter/issues/3966

**Comment by warpech** [comment]
@Mackiovello do you think you could take this?

**Comment by Mackiovello** [comment]
@warpech 
Do we possibly have an example where this is done so I can see how it should be?

**Comment by warpech** [comment]
Instead of every `Self.GET(UriMapping.MappingUriPrefix + "` and `Self.GET<Json>(UriMapping.MappingUriPrefix + "` there should be a `Self.GET("/launcher` or `Self.GET<Json>("/launcher`

You will need to create `Handle.GET("/launcher` for these requests.

And you will need to add a new file `Map.cs` that has `UriMapping.Map` for every of these calls. Similarly how it is done here: https://github.com/StarcounterSamples/Products/blob/a526e691be1379462563c6e9f1e700b26763fd3f/src/Products/Api/LauncherHooks.cs

**Comment by warpech** [comment]
Fixed in #257
