### ISSUE TITLE
Remove JavaScript test

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#255]
The JavaScript test in `test/test.js` is no longer needed. Remove it, as well as any mentions of it from BAT, MD and JSON files in the repo.

**Comment by warpech** [comment]
cc @alemoi, @joozek78

**Comment by alemoi** [comment]
I checked it and wonder if whole folder `test` is in use?
![image](https://cloud.githubusercontent.com/assets/208134/20611122/978a1f0c-b2a4-11e6-8387-d5ec3b6bae17.png)

**Comment by warpech** [comment]
Yes it is used big time by https://github.com/StarcounterPrefabs/Launcher/blob/master/launcher_selenium_test.bat.

Only `test.js` should be removed from this folder.

**Comment by warpech** [comment]
Pls remember that we work on pull requests done with feature branches started from develop branch. 

Thanks!

**Comment by alemoi** [comment]
Here you go: https://github.com/StarcounterPrefabs/Launcher/pull/256
:smile:

**Comment by warpech** [comment]
Thanks! Merged
