### ISSUE TITLE
Move CompositionProvider and CompositionEditor to separate repos, release a version

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#263]
Follow up from PR https://github.com/StarcounterPrefabs/Launcher/pull/259#issuecomment-269080600: Move CompositionProvider and CompositionEditor to separate repos (in Starcounter org).

- [x] Create the CompositionProvider repo and copy the code from Launcher
- [x] Create the CompositionEditor repo and copy the code from Launcher
- [x] Delete CompositionProvider and CompositionEditor from Launcher
- [x] Release CompositionProvider 1.0.0, CompositionEditor 1.0.0, Launcher 6.0.0

@tomalec do you have something against the last point?

**Comment by tomalec** [comment]
LGTM.

Just to note, https://github.com/Starcounter/CompositionProvider is already there, but please review what I've done :)

**Comment by warpech** [comment]
Created https://github.com/Starcounter/CompositionEditor

**Comment by warpech** [comment]
Point 3 tracked in https://github.com/StarcounterPrefabs/Launcher/pull/264

**Comment by warpech** [comment]
All done!

**Comment by warpech** [comment]
Release notes published.
