### ISSUE TITLE
Wrong position of Composition Editor icon by default

### ISSUE THREAD

**Issue by mmnosek** [StarcounterPrefabs/Launcher#265]
Since Composition Editor has been moved from Launcher to the separate app, icon position is incorrect - it's shown above user avatar. It should be displayed just before gear icon in one line.

Screenshoot:
<img width="1439" alt="launcher-composition-editor" src="https://cloud.githubusercontent.com/assets/4943949/22030238/520a368e-dcdd-11e6-9357-7ac82b0d37f2.png">

cc @warpech

**Comment by warpech** [comment]
PR #266

**Comment by mmnosek** [comment]
Thanks!
