### ISSUE TITLE
Automatic virtual groups for package.js based on apps, templates, runs

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#33]
Automatic virtual groups for package.js based on apps, templates, runs

This is not required for the demo.

**Comment by miyconst** [comment]
It might be right time to address this issue.

**Comment by warpech** [comment]
I think that this issue was a conceptual grandparent for https://github.com/Starcounter/RebelsLounge/issues/14 and can be closed now. @tomalec do you agree?

**Comment by tomalec** [comment]
Yep, that is probably a grandparent :)

However I think, this issue adds a fair point, that we may consider adding all elements given by an app, into a group, if  we do not want to do so, we can close this issue.

**Comment by warpech** [comment]
Closing, because it is related to the old layout editor which was phased out.
