### ISSUE TITLE
Elements should be added as level 3

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#37]
Currently elements are added to "root" group by default.

I think it should go further and actually elements should be added as level 3 group:

- "rootMargin" group with gap 24 -- for wide margin around whole workspace
  - "root" group with gap 16 -- for space between actual root elements
    - element0
    - element1
    - element2

**Comment by miyconst** [comment]
@warpech is this issue still up to date?

**Comment by warpech** [comment]
This issue was about a way to change the padding around the outermost `juicy-tile-grid` in the layout editor. But this is not feasible, it needs to be done in Launcher's CSS. Closing
