### ISSUE TITLE
Input background should be transparent by default

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#53]
For elements that appear in the workspaces, the text input, textarea background should be transparent unless app designer implicitly sets otherwise

**Comment by miyconst** [comment]
@warpech is this issue is still up to date? I don't see a reason why should `<input type="text" />` and `<textarea></textarea>` be on transparent background.

**Comment by warpech** [comment]
The reason for this issue was that if I have an `<input>` and decided to change the grid cell background to orange, I end up with an orange background with a big white rectangle.

But I agree we should not apply any magic.

Our current Bootstrap theme (Bootswatch Paper) actually sets the background to all `.form-control` to be `transparent`, so this is indirectly fixed.

Regular Bootstrapp sets `.form-control` background to `#fff` though.

Closing this as a non-issue
