### ISSUE TITLE
Increment/decrement buttons

### ISSUE THREAD

**Issue by Starcounter-Jack** [StarcounterPrefabs/Launcher#56]
Let's try the default value of increments of 4. I.e.

```
4
8
12
16
20
24
etc.
```

**Comment by miyconst** [comment]
We don't have width/height increment button in the new editor. Should this logic be applied to gutter and oversize?

**Comment by warpech** [comment]
Gutter and oversize should increment and decrement by 1.

This issue is made obsolete by the simple layout editor. Closing
