### ISSUE TITLE
Default gaps are set to zero

### ISSUE THREAD

**Issue by Starcounter-Jack** [StarcounterPrefabs/Launcher#60]
By default, the gaps should be set to a value smaller than the higher gap in the hierarchy.
I have not visually tried the default values below, but let's start there.

```
Workspace margin:  32px
Gap Level 1          :   16px
Gap Level 2          :   8px
Gap Level 3          :   4 px
Gap Level 4          :   4 px
Gap Level 5          :   4 px
etc.
```

**Comment by tomalec** [comment]
At today's (2015-08-04) meeting we agreed to set gutter to half of a parent by default.

**Comment by warpech** [comment]
Closing, because it is related to the old layout editor which was phased out.
