### ISSUE TITLE
[Layout Editor] Custom CSS

### ISSUE THREAD

**Issue by Starcounter-Jack** [StarcounterPrefabs/Launcher#75]
It would be nice to have an edit box for styles for each selected element. I.e. without the need for a selector.

``` css
background: blue;
```

Also it would be nice to be able to turn the parent element into a real DOM element to provide custom CSS.

**Comment by miyconst** [comment]
@Starcounter-Jack, @tomalec is this issue still up to date?

**Comment by tomalec** [comment]
Right now we do have Shadow DOM wrappers, so we can attach custom CSS to the tiles.

I think we still aim to render plain CSS, that could be changed/overwritten by advanced designer.

**Comment by tomalec** [comment]
Now, it's solved by Juicy/juicy-composition - we are attaching `DocumentFragment` with anything that HTML allows to the Shadow DOM of a partial, so we can attach custom style sheets as `<style>` tag with inline or external content, we can use `style` attributes an much more.

For more details see https://starcounter.io/layout-compositions-html-partials/
