### ISSUE TITLE
Create breakpoints picker/slider

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Launcher#81]
We can create new `juicy-` web component, to pick media-query breakpoint for `juicy-tiles` configuration that would look similar to 
![Adobe one](http://html.adobe.com/_/img/edge/reflow/edge_reflow_feature-sm_visualmediaqueries.png)

**Comment by miyconst** [comment]
Done in the new editor.

![image](https://cloud.githubusercontent.com/assets/6435556/13173052/b36cd6e0-d6fb-11e5-8085-ad270699a90c.png)
