### ISSUE TITLE
Launcher editor overlay causes high CPU usage

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#83]
When I open the editor in the Launcher, the CPU usage gets high.

I think this is connected with https://github.com/juicy/juicy-highlight, which redraws SVG on requestAnimationFrame

**Comment by miyconst** [comment]
This issue was fixed in since this commit: [Don't render svg if its path has not been changed](https://github.com/Juicy/juicy-highlight/commit/fb2ed9a7038fe4fff56de6d98774b990a52a388e).
