### ISSUE TITLE
Static-openstreetmap high CPU usage

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#84]
Similarily to #83, `<static-openstreetmap>` is using requestAnimationFrame to detect size changes. It should be done in less invasive way.

Possible solution: https://github.com/juicy/juicy-tile-list/issue/6

**Comment by miyconst** [comment]
What is `<static-openstreetmap>`?

**Comment by warpech** [comment]
A relic of the past :)
