### ISSUE TITLE
How to store and serve configuration (layout, and other meta) for tiles, that may be added and removed (filter)?

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Launcher#86]
In regards of #16, #39, and #78 we need to decide where, and how to store `<juicy-tile-list>` configuration. It would be also nice to keeps other meta data for future stuff.

Problems to address:
1. Tiles may appear or disappear according to filter (#16),
2. Tiles may be added or removed by app developer,
3. We plan to give opportunity to prepare different layouts according to responsive design break points (#39),
4. We could like to use different setup for same `html` used in many partials(handlers),
5. App/widget/tile code should not be aware of any part of our magic,
6. Layout should be kept, even if content of tile changes (i18n, 'dynamic' content)

**Comment by warpech** [comment]
Archiving. Right now the config is saved in the database.
