### ISSUE TITLE
Way to identify mergeable page/partial vs standalone

### ISSUE THREAD

**Issue by tomalec** [StarcounterPrefabs/Launcher#90]
Currently we identify whether to merge responses or not by checking if response has `GetHtmlPartialUrl` method ([/Server/Launcher.json.cs#L78](https://github.com/Polyjuice/Launcher/blob/master/Server/Launcher.json.cs#L78)
I wonder if it is the best way to do so, as I believe that someone would like to return a JSON without such method, and personally I does not find adding such method intuitive, and I've get stuck few times wondering why my app output does not appear as mergeable result.

Maybe we could use `MergeableJson` class or `json.mergable` flag for such cases?

**Comment by miyconst** [comment]
@tomalec is this issue still up to date?

**Comment by tomalec** [comment]
@warpech It's solved by your implicit standalone mode, isn't it?

The only question is what about improvements of check whether it's a partial or not.

**Comment by warpech** [comment]
If using implicit standalone mode, the app does not have to care if it is running standalone. Implicit standalone mode will wrap it.

Right now the check is based on the presence of `<!doctype`, which might be improved in future: https://github.com/Starcounter/Starcounter/blob/81c9a245f2f3769cb19bb2e2ad0c3d69a14b19b8/src/Starcounter/Middleware/PartialToStandaloneHtmlProvider.cs#L105
