### ISSUE TITLE
Load layouts as CSS until layout editor is brought on screen

### ISSUE THREAD

**Issue by warpech** [StarcounterPrefabs/Launcher#99]
Layouts should be saved in both JSON and CSS format. The CSS format should be used for rendering by default.

Discussed with @Starcounter-Jack and @tomalec on Monday

**Comment by tomalec** [comment]
As mentioned in https://github.com/Juicy/juicy-tile-grid/issues/12, with tight groups we will need to provide also non-CSS layout with at least nested groups structure.

**Comment by warpech** [comment]
Closing, because it is related to the old layout editor which was phased out.
